version: '3.3'
services:
 grafana:
   container_name: "grafana"
   image:  grafana/grafana:5.4.3
   restart: unless-stopped
   user: "104"
   ports:
      - $GRAFANA_PORT:3000
   volumes:
       - ./grafana:/var/lib/grafana
 influxdb:
   container_name: "influxdb"
   image: influxdb:1.5.4
   volumes:
        - ./influxdb:/var/lib/influxdb
   ports:
        - 8086:8086
   environment:
        - INFLUXDB_DB=$INFLUXDB_DB
        - INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
        - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
        - INFLUXDB_USER=$INFLUXDB_USER
        - INFLUXDB_USER_PASSWORD=$INFLUXDB_USER_PASSWORD
        
 telegraf:
   container_name: "telegraf"
   image: telegraf:1.11
   depends_on:
       - influxdb
   volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
